[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/{{gh-username}}/{{project-name}}"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
